FROM node:10.15.3 as builder
WORKDIR /work

ADD fe/package.json .
ADD fe/package-lock.json .
ADD fe/webpack.config.js .

RUN npm ci

ADD fe/src src

RUN npx webpack

FROM nginx:stable-alpine as runner
RUN apk add --no-cache bash sed coreutils
ADD fe/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /work/dist public
EXPOSE 80
ENTRYPOINT ["bash", "-c", "nginx -g \"daemon off;\""]
