version: '3'
services:
  frontend:
    image: 991180925719.dkr.ecr.ap-northeast-1.amazonaws.com/fe-sinatra-todo
    ports: 
      - "4200:80"
    links:
      - sinatra-api-server
  sinatra-api-server:
    image: 991180925719.dkr.ecr.ap-northeast-1.amazonaws.com/be-sinatra-todo
    environment:
      RACK_ENV: production
    expose:
      - "4567"
    ports: 
      - "4567:4567"
    volumes:
      - "bundle:/usr/local/bundle"

volumes:
  bundle: