require 'rubygems'
require 'bundler'
Bundler.require

require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'
require './models/todo.rb'

require 'dotenv'
require 'erb'
require 'yaml'

Dotenv.load
yaml = YAML.load(ERB.new(File.read("./database.yml")).result)

ActiveRecord::Base.configurations = yaml
ActiveRecord::Base.establish_connection(:default)
